#!/bin/bash
source .env
dedupe_id=$RANDOM-amonzo-expronzo
pots=$(http "https://api.monzo.com/pots" "Authorization: Bearer $access_token" )
code=$(echo -n $pots | jq -r .code)
if [ "$code" == "unauthorized.bad_access_token.expired" ]; then
	if [ -z "$refresh_token" ]; then
		echo 'BAD POPO: $access_token expired and no $refresh_token, gotta get gint'
		exit 1
	fi
	response=$(http --form POST "https://api.monzo.com/oauth2/token" \
		"grant_type=refresh_token" \
		"client_id=$client_id" \
		"client_secret=$client_secret" \
		"refresh_token=$refresh_token")
	echo $response
	access_token=$(echo $response | jq -r .access_token)
	refresh_token=$(echo $response | jq -r .refresh_token)
	echo "access_token=\"$access_token\"" >> .env
	echo "refresh_token=\"$refresh_token\"" >> .env
fi
current_pot_value=$(echo -n $pots | jq ".pots[] | select(.id==\"$pot_id\") | .balance")
echo "there's currently $current_pot_value pennies in the amex pot"
current_balance=$(($(node get-balance.js) * 100))
echo "the amex balance is $current_balance pennies"
increase=$((current_balance - current_pot_value))
echo "that's an increase of $increase pennies"

if [ -z "$current_balance" ]; then
	exit 11
fi

if [ $increase -lt 1 ]; then
	echo "that's less than a penny, so im doin nothin"
	exit
fi

http --form PUT "https://api.monzo.com/pots/$pot_id/deposit" \
	"Authorization: Bearer $access_token" \
	"source_account_id=$account_id" \
	"amount=$increase" \
	"dedupe_id=$dedupe_id" > /dev/null

echo "transaction complete!!"
current_pot_value=$(http "https://api.monzo.com/pots" "Authorization: Bearer $access_token" | jq ".pots[] | select(.id==\"$pot_id\") | .balance")
echo "there's now $current_pot_value pennies in the pot ^_^"

http --form POST "https://api.monzo.com/feed" \
	"Authorization: Bearer $access_token" \
	"account_id=$account_id" \
	"type=basic" \
	"params[title]=£$((increase / 100)) - American Express" \
	"params[image_url]=https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/American_Express_logo.svg/1024px-American_Express_logo.svg.png" \
	"params[background_color]=#fefefe" \
	"params[body_color]=#333" \
	"params[title_color]=#333" \
	"params[body]=$increase pennies moved to amex pot 💅" > /dev/null
